### ISSUE TITLE
Where are decimalToBinaryVector and binaryVectorToDecimal ?

### ISSUE THREAD

**Issue by ichenxing** [kirk86/wateramarking#1]
when i run dwt_svm.m, the error is following as:

??? Undefined function or method 'decimalToBinaryVector' for input arguments of type
'double'.

Error in ==> signature_embedding at 51
    binary_coefficients{p} = decimalToBinaryVector(integer_part(p), 16);

Error in ==> watermark_embedding at 57
LL_inv = signature_embedding(LL, signature, print_figures);

Error in ==> dwt_svd at 47
    watermarked_image = watermark_embedding(cover_image, watermark_logo, ...

i want to replace these function to dec2bin and bin2dec, but in bin2dec, the error is Binary string may consist only of characters 0 and 1, so i hope for your help!!!

**Comment by kirk86** [comment]
The "decimalToBinaryVector" and "binaryToDecimalVector" if I remember correctly are native matlab functions in version 2012b or 2013b, but if in case you don't have them then you can use the alternative natives such as "bin2dec" and "dec2bin" as you already mentioned. Since "bin2dec" is a function that accepts only string inputs you'll also have to wrap the input vector as a string using either the "string" function or the "char" one. On the other hand the "dec2bin" function accepts only integer inputs so make sure that whatever you pass to it is in a integer format. See also the matlab manual on both functions. Hope that helps solve your problem.

**Comment by ichenxing** [comment]
Thank you for your help, and your reply is very useful to me!!!

**Comment by skycon786** [comment]
i have tried  binaryToDecimalVector to bin2dec but it again display the same error. I have also converted the vector into char by using char, mat2str etc. function, but it does't help me. please provide a solution to sole this issue.

 bin2decimal(x) = bin2dec(char(binary_coefficients{1, x}));

**Comment by kirk86** [comment]
Hi @skycon786. What matlab version are you using? Do you have binaryToDecimalVector in your system?

**Comment by skycon786** [comment]
I m using Matlab R2012a

**Comment by kirk86** [comment]
Oh boy! I am using 2016a now but the principles should be the same, you shouldn't be affected by the following solution.

let's say that we create a binary vector x with 5 elements
`x = repmat([0 1], 1, 5)`
now you should be in position to easily transform that into a decimal with the following code
`y = bin2dec(int2str(x))`
the above code gives you a decimal number, to verify that the conversion was correct you can transform it back again to a binary number and check if it is the same as x
`dec2bin(y)`.
