### ISSUE TITLE
"You might not have write permission" Error

### ISSUE THREAD

**Issue by jahani** [kirk86/wateramarking#2]
When `watermarked_images`, `attacked` and `logos` folders doesn't exist in the directory, the program corrupts with this error:

```
Error using imwrite (line 454)
Unable to open file "E:\wateramarking-master\watermarked_images\1.png"
for writing.  You might not have write permission.

Error in dwt_svd (line 75)
        imwrite(uint8(watermarked_image), watermarked_images_dir, 'png');
```

The program should create this folders when they doesn't exist.
_MATLAB R2015a_

**Comment by kirk86** [comment]
Well if you read also the comments from [matlab file exchange central repository](http://www.mathworks.com/matlabcentral/fileexchange/41686-dwt-svd-robust-and-secure-watermarking-scheme) you would have noticed from the discussions and comments of other users that creating the folders is a requirement for the program to work in this case. At moment thats how it works if you want the folders to be created by the program then why don't you add that feature in order to contribute?
